//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundBoard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoundBoard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta lang=&quot;en&quot;&gt;
        ///        &lt;title&gt;Main&lt;/title&gt;
        ///        &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;navbar.css&quot; /&gt;
        ///        &lt;link type=&quot;text/css&quot; rel=&quot;stylesheet&quot; href=&quot;soundboard.css&quot; /&gt;
        ///        &lt;script src=&quot;script.js&quot;&gt;&lt;/script&gt;
        ///    &lt;/head&gt;
        ///    &lt;body onload=&quot;start()&quot;&gt;
        ///        &lt;main&gt;
        ///            &lt;div class=&quot;grid&quot; id=&quot;grid&quot;&gt;
        ///            &lt;/div&gt;
        ///        &lt;/main&gt;
        ///
        ///        &lt;nav class=&quot;navbar&quot;&gt;
        ///            &lt;ul class=&quot;navbar-nav&quot;&gt;
        ///                &lt;li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon launchpad {
            get {
                object obj = ResourceManager.GetObject("launchpad", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :root {
        ///    font-size: 16px;
        ///    --transition-speed: 500ms;
        ///    --text-primary: #b6b6b6;
        ///    --text-secondary: #ececec;
        ///    --bg-primary: #23232e;
        ///    --bg-secondary: #141418;
        ///    --svg-primary: #ff7eee;
        ///    --svg-secondary: #df49a6;
        ///}
        ///
        ///body {
        ///    margin: 0;
        ///    padding: 0;
        ///}
        ///
        ///body::-webkit-scrollbar {
        ///    width: 0.5rem;
        ///}
        ///
        ///body::-webkit-scrollbar-track {
        ///    background: #1e1e24;
        ///}
        ///
        ///body::-webkit-scrollbar-thumb {
        ///    background: #6649b8;
        ///    border-radius: 0.25rem;
        ///}
        ///
        ///main {
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string navbar {
            get {
                return ResourceManager.GetString("navbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///    font-size: 22px;
        ///    margin: 0;
        ///}
        ///
        ///div.content {
        ///    width: 100vw;
        ///}
        ///
        ///ul {
        ///    transition: width 3s;
        ///    display: inline;
        ///    padding-inline-start: 0;
        ///    text-align: center;
        ///}
        ///
        ///li {
        ///    list-style: none;
        ///    background: #d1703c;
        ///    color: #fff;
        ///    height: 0;
        ///    line-height: 2em;
        ///    margin: 0;
        ///    padding: 0 1em;
        ///    overflow: hidden;
        ///
        ///    border-bottom-left-radius: 0;
        ///    border-bottom-right-radius: 0;
        ///    transition: width 3s, border-bottom-left-radius 1s, border [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nowPlaying_css {
            get {
                return ResourceManager.GetString("nowPlaying.css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;title&gt;SoundBoard Now Playing&lt;/title&gt;
        ///        &lt;link rel=&quot;icon&quot; href=&quot;favicon.ico&quot;&gt;
        ///        &lt;script src=&quot;nowPlaying.js&quot;&gt;&lt;/script&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; href=&quot;nowPlaying.css&quot;&gt;
        ///    &lt;/head&gt;
        ///    &lt;body onload=&quot;start()&quot;&gt;
        ///        &lt;div class=&quot;content&quot;&gt;
        ///            &lt;ul id=&quot;list&quot; class=&quot;slide-fade&quot;&gt;&lt;/ul&gt;
        ///        &lt;/div&gt;
        ///    &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string nowPlaying_html {
            get {
                return ResourceManager.GetString("nowPlaying.html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var oldjson;
        ///var displaying = new Object();
        ///var timeStep = 1000;
        ///var lastElement;
        ///
        ///function start() {
        ///    if (timeStep) {
        ///        statusLoop();
        ///    }
        ///}
        ///
        ///function statusLoop() {
        ///    var httpRequest = getRequest();
        ///    try {
        ///        httpRequest.open(&quot;GET&quot;, &quot;playing.html&quot;, true);
        ///        httpRequest.onreadystatechange = function () {
        ///            if (httpRequest &amp;&amp; httpRequest.readyState === 4 &amp;&amp; httpRequest.responseText) {
        ///                if (httpRequest.responseText.charAt(0) !== &quot;&lt;&quot;) {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nowPlaying_js {
            get {
                return ResourceManager.GetString("nowPlaying.js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var httpRequest;
        ///var timeStep = 1000;
        ///var path;
        ///var shouldUpdate = false;
        ///var buttons = new Array();
        ///
        ///function createButton(song, title, isBack) {
        ///    if (isBack === void 0) { isBack = false; }
        ///    var span = document.createElement(&quot;span&quot;);
        ///    var a = document.createElement(&quot;a&quot;);
        ///    a.className = &quot;button&quot;;
        ///    a.href = &quot;#&quot;;
        ///    var div = document.createElement(&quot;div&quot;);
        ///    var p = document.createElement(&quot;p&quot;);
        ///    p.innerHTML = isBack ? &quot;&amp;#128281;&quot; : title;
        ///    div.append(p);
        ///    a.append(di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string script {
            get {
                return ResourceManager.GetString("script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :root {
        ///    --font-primary: #d3d3d3;
        ///    --font-secondary: #ececec;
        ///    --background: #494953;
        ///    --background-secondary: #73727a;
        ///    --background-trinary: #23232e;
        ///    --background-playing-primary: #733f3b;
        ///    --background-playing-secondary: #4E1313;
        ///    --background-fav-primary: #484716;
        ///    --background-fav-secondary: #92901b;
        ///    --background-dir-primary: #391b00;
        ///    --background-dir-secondary: #552900;
        ///}
        ///
        ///body {
        ///    background: var(--background);
        ///}
        ///
        ///main {
        ///    padding: 1.368vw;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string soundboard {
            get {
                return ResourceManager.GetString("soundboard", resourceCulture);
            }
        }
    }
}
